### ISSUE TITLE
Cannot find ASAP_embedding_CLRadt.rds file

### ISSUE THREAD

**Issue by XiHuYan** [jaydu1/scVAEIT#2]
Hi, I'm trying to reproduce your experiment on the DOGMA-seq dataset. I tried to download the specified files from your provided link [https://github.com/caleblareau/asap_reproducibility](gitrepo), but I cannot find the last file ASAP_embedding_CLRadt.rds. Could you provide the download link?

**Comment by jaydu1** [comment]
Hi, thanks for the question. Apperantly, the authors of that repo modified the files after we downloaded the data.
<img width="609" alt="Screenshot 2023-07-31 at 08 39 42" src="https://github.com/jaydu1/scVAEIT/assets/25794386/8bea4116-5ecc-4c4c-a65b-46a7aa8e15ab">
I can share with you this rds file through email privately. Can you provide me with your email, or can you send a email to jinhongd@andrew.cmu.edu so that I can sent it to you?

**Comment by XiHuYan** [comment]
***@***.*** This is my email. Thanks :-)




严旭画
***@***.***







                       
Original Email
                       
                     

Sender:"Du Jinhong"< ***@***.*** &gt;;

Sent Time:2023/7/31 20:45

To:"jaydu1/scVAEIT"< ***@***.*** &gt;;

Cc recipient:"XiHuYan"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [jaydu1/scVAEIT] Cannot find ASAP_embedding_CLRadt.rds file(Issue #2)




 
Hi, thanks for the question. Apperantly, the authors of that repo modified the files after we downloaded the data.
 
 I can share with you this rds file through email privately. Can you provide me with your email, or can you send a email to ***@***.*** so that I can sent it to you?

**Comment by jaydu1** [comment]
Sorry I cannot see the email address from your reply. Not sure if this is because of seurity reason when you reply through email. Can you send it again on the web?
