### ISSUE TITLE
Question about masks?

### ISSUE THREAD

**Issue by XiHuYan** [jaydu1/scVAEIT#3]
Hi, I reproduced the demo, but I have one question about obtaining latent representations:
Why did you input `masks_ADT` to `update_z()`?
```
# only utilize proteins
masks_ADT = masks.numpy().copy()
masks_ADT[:, model.vae.config.dim_input_arr[0]] = -1.
masks_ADT[:,-model.vae.config.dim_input_arr[2]:] = -1.
masks_ADT = tf.convert_to_tensor(masks_ADT, dtype=tf.float32)
model.update_z(masks_ADT)
```
Can I directly input the `masks.numpy()` to `update_z()`?

**Comment by jaydu1** [comment]
Thanks for the question. 

When using different masks, we can obtain different embeddings for the same cell.
It is fine if we directly use all the modalities, but then the embeding will also contain info from RNA or ATAC. This will make the latent representation of cells from different datasets slightly different (because they contain info of different modalities).
Here, to better align cells from different datasets and for better visualization, we only use the proteins.

This also reminds me of some interesting directions. If we use the protein embedding for two datasets $E_{ADT}^{(1)}$ and $E_{ADT}^{(2)}$ as the baseline, we may get the prediction of embedding for other modality; for instance, obtain $\hat{E}\_{RNA}^{(2)}$ from kNN of $E_{RNA}^{(1)}$, where the distance is measured based on $E_{ADT}^{(1)}$ and $E_{ADT}^{(2)}$. This idea can be used either for training (as one term of the losses), or for inference (for improving the predictive performance). Thanks for the great questions!

**Comment by XiHuYan** [comment]
Thanks :-)

**Comment by ikonsta** [comment]
Does it mean that there is no way to fully integrate (without "batch" effect) different datasets using your model, if those datasets are not matching even in one modality?

**Comment by jaydu1** [comment]
At least some datasets have to overlap a little bit, so that the model can learn some relationship between modalities. However, this does not require all the datasets to share the same modality. But If you do have such datasets, it certainly helps to align them better.

**Comment by ikonsta** [comment]
Thanks for your answer. I just want to clarify, if I have datasets that overlap a little bit I can train the model using all features (from the modality that is a bit different between datasets), but then should I use only overlapping features to get the latent space, or can I use all features? Or even during the training, I should use only overlapped features?

**Comment by jaydu1** [comment]
Yes, you can use all the fratures for both training and extreacting latent variables. For instance, If you have three datasets:

Datasets 1 A   B    NA
Datasets 2 A   NA C
Datasets 3 NA B   C

where A B C are three modalities. It still works. In this case, when extracting latent variables, you can only rely on features observed in the specified datasets.

**Comment by JiahaoChow** [comment]
It appears that using` model.update_z(masks_ADT)` utilizes all observed data. If we want to obtain embeddings for a specific modality, should we manually mask the input beforehand?

**Comment by jaydu1** [comment]
Hi, there is an optional argument `mask` to the function `model.update_z`: see [function definition in code](https://github.com/jaydu1/scVAEIT/blob/86b372fc2a1e69abb59f4874fca7ff1286a2161c/scVAEIT/VAEIT.py#L286).

**Comment by JiahaoChow** [comment]
Thanks! I notice that the `mask` is updated through the optional argument `mask`. However, `x` for the encoder is still the fully observed data. If I want to obtain the embedding for ADT, should I mask both `x` and `mask` before calling `vae.get_z()`?

**Comment by jaydu1** [comment]
Thanks for pointing out the issue. Ideally, `x` should also be masked within the function `vae.get_z()`. I will fix this bug, provide an optional argument to mask out `x`, and evaluate the results of the two scenarios soon.

**Comment by JiahaoChow** [comment]
Thank you.

**Comment by jaydu1** [comment]
Hi, @JiahaoChow. That should be a bug in the earlier version of the package. 
If you use scVAEIT for your own research, please check out the latest version [v1.0.0](https://github.com/jaydu1/scVAEIT/releases/tag/v1.0.0), which fixes the bug and includes several improvements over the earlier implementation. The corresponding weight files are available for running [example/integration_3modalities.ipynb](https://github.com/jaydu1/scVAEIT/blob/main/example/integration_3modalities.ipynb).
